name: Test Common Secret Keys

on: push

jobs:
  secret_tester:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}  # ✅ Explicitly pass the secret
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: 🔍 Testing Common Secret Keys
        run: |
          echo "🔎 Checking AWS_ACCESS_KEY_ID..."
          if [ -n "$AWS_ACCESS_KEY_ID" ]; then
            echo "✅ AWS_ACCESS_KEY_ID Found (length: ${#AWS_ACCESS_KEY_ID})"
          else
            echo "❌ AWS_ACCESS_KEY_ID is empty or not set"
          fi
