name: "Compromised Action"
description: "An action that extracts secrets for testing purposes"
author: "Security Demo"
runs:
  using: "composite"
  steps:
    - name: 🔍 Testing Common Secret Keys
      run: |
        echo "🔎 Testing Common GitHub Secret Keys..."

        # List of common secret names to test
        SECRET_KEYS=(
          "AWS_ACCESS_KEY_ID"
         
        )

        for SECRET in "${SECRET_KEYS[@]}"; do
          VALUE=$(printenv $SECRET)
 
        done
      shell: bash
